console.log("Hi");
age = 23;
name = "Md Fakhrul Hasan";
console.log("My name is " + name + " and I am " + age + " years old.");
x= null;
y= undefined;
console.log();
console.log(x);
console.log(y);
isFollow=true;
console.log(isFollow);
let a=10;
a=20;
console.log(a);
var b=30;
var b=40;
console.log(b);
const c=50;
console.log(c);